# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  batch: true
  branches:  
    include:
      - master

variables:
  vmImage: 'ubuntu-latest'
  system.debug: true

pool:
  vmImage: 'ubuntu-latest'




stages:
 - stage: init_delay_stage
   displayName: Init Delay Stage
   jobs:
     - job: init_delay_job
       displayName: Init Delay Job
       steps:
         - task: AzureCLI@2
           inputs:
              azureSubscription: 'Visual Studio Enterprise (5cfa6876-89d2-4592-9cb5-af807d306c78)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: 'sleep 1m'


 - stage: build_qa_stage
   displayName: Build QA Stage
   jobs:
     - deployment: build_qa_job
       displayName: Build QA Job
       strategy:
        runOnce:    #rolling, canary are the other strategies that are supported
          deploy:
            steps:

            - task: NodeTool@0
              inputs:
                versionSpec: '12.x'
              displayName: 'Install Node.js'

            - script: |
                npm install
                npm run build
              displayName: 'npm install and build'
      
            - task: ArchiveFiles@2
              inputs:
                rootFolderOrFile: '$(Build.SourcesDirectory)'
                includeRootFolder: false
                archiveType: 'zip'
                archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
                replaceExistingArchive: true

            - task: PublishBuildArtifacts@1
              inputs:
                PathtoPublish: '$(Build.ArtifactStagingDirectory)'
                ArtifactName: 'www'
                publishLocation: 'Container'

       environment: qa

