# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
  vmImage: 'ubuntu-latest'
  system.debug: true

pool:
  vmImage: 'ubuntu-latest'

stages:
 

 - stage: deploy_prod_stage
   displayName: Deploy PROD Stage
   jobs:
    - deployment: deploy_prod_job
      displayName: Deploy PROD Job
      strategy:
        runOnce:    #rolling, canary are the other strategies that are supported
          deploy:
            steps:

            - task: AzureAppServiceManage@0
              displayName: Swap Staging-PROD Slot
              inputs:  
                azureSubscription: 'Visual Studio Enterprise (5cfa6876-89d2-4592-9cb5-af807d306c78)'
                Action: 'Swap Slots'
                WebAppName: 'mg-function-app-002'
                ResourceGroupName: 'mohit-azure-group'
                SourceSlot: 'staging'

            - task: AzureCLI@2
              displayName: Delete Staging Slot
              inputs:
                azureSubscription: 'Visual Studio Enterprise (5cfa6876-89d2-4592-9cb5-af807d306c78)'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: 'az functionapp deployment slot delete --name mg-function-app-002 --resource-group mohit-azure-group --slot staging'

      environment: qa 


